@Library("shared-library") _

pipeline {
    agent any
    environment {
        CI = 'true'
        PATH = "/usr/local/bin:/usr/bin:/bin:/sbin"
        APP_NAME="tic-tac-toe"
    }
    stages {
        stage('Init') {
            steps {
                helloWorld(dayOfWeek: "Thursday", name: "John")
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'node:21.6.1'
                    args '-p 3000:3000'
                }
            }
            steps {
                echo "start build"
                sh 'yarn && yarn build'
                script {
                    sh("ls ./app/frontend")
                }
                stash includes: 'app/frontend/dist/**/*', name: 'builtSourceFrontEnd'
                stash includes: 'app/server/dist/**/*', name: 'builtSourceServer'
                echo "done build"
            }
        }
        stage('Containerise') {
            steps {
                echo "start containerise"
                dir('.'){
                    unstash 'builtSourceFrontEnd'
                    unstash 'builtSourceServer'
                }
                script {
                    sh("ls -R ./app/frontend/dist")
                    dockerBuild.build(env.APP_NAME)
                }
                echo "done containerise"
            }
        }
        // stage('Push') {
        //     steps {
        //         script {
        //             dockerBuild.push(env.APP_NAME)
        //         }
        //     }
        // }
    }
}